### PR TITLE
import godotenv as a subpackage

### PR DESCRIPTION
**Pull request by ndeloof**
This makes https://github.com/compose-spec/godotenv a subpackage in compose-go, as we diverged from original forked joho/godotenv to match compose requirements. This will also makes test and release process simpler

note: MIT license uses by godotenv allows relicensing into Apache. Another option would be to relicense compose-go as MIT.

see https://cloud-native.slack.com/archives/C01162AJ23C/p1639033869024300 for context

### CODE REVIEW

**Comment by mat007** [comment]
I don’t think we can or should do it quite like that, we probably want at least to retain the original license file and copyright, adding that file to the folder should be enough: https://github.com/joho/godotenv/blob/master/LICENCE
Also what can’t re-license because we’re not the copyright holders.

**Comment by ndeloof** [comment]
> we can’t re-license godotenv

we can, this is allowed by MIT license
> Permission is hereby granted to deal in the Software .. without limitation the rights to ... sublicense

but I'm fine to include the original LICENSE file in this subdirectory if you feel this is required

**Comment by mat007** [comment]
>> we can’t re-license godotenv

> we can, this is allowed by MIT license

It allows anyone to sublicense, which is a little different 😬

**Comment by ndeloof** [comment]
added original LICENSE as suggested

**Review by mat007 — COMMENTED** [review]
That looks OK, this means we think we have diverged so much we’ll never be able to use upstream godotenv anyway, right?

**Comment by ndeloof** [comment]
yes indeed. Also upstream project isn't very active, and initial PR https://github.com/joho/godotenv/pull/149 from @ulyssessouza (6 months old) still has no comment regarding possible approval

**Review by mat007 — APPROVED** [review]
All right!

It’s a bit of a shame, given how little code there is in dotenv maybe we should have written this from scratch from the beginning… 😁

**Comment by ndeloof** [comment]
Agree.
Still an option if you have some spare time

**Review by ulyssessouza — APPROVED** [review]
LGTM

**Comment by ndeloof** [comment]
I've archived compose-spec/godotenv repository so we avoid mistakes merging stuff on the wrong side

**Pull request merged**
