### PR TITLE
Revert "run interpolation after merge, but for required attributes"

### PR DESCRIPTION
**Pull request by idsulik**
This reverts commit 65600cee45d45771a1faa6ddaf87b23ca4d2400c.

The commit led to this issue https://github.com/docker/compose/issues/12001, a quick fix is to revert the commit and release it.

### CODE REVIEW

**Comment by ndeloof** [comment]
We only do such revert if there's no reasonable fix to offer.
For those impacted it is easy to just keep running older docker compose release

**Comment by idsulik** [comment]
> We only do such revert if there's no reasonable fix to offer. For those impacted it is easy to just keep running older docker compose release

Okay, I got it. It was just a quick fix.  I think it'll be better to revert and release if we don't be able to fix it asap, because more and more users download the latest version and a lot of them will be forced to downgrade or spent time figuring out what went wrong

**Comment by ndeloof** [comment]
Sure. A fix is proposed by @jhrotko here : https://github.com/compose-spec/compose-go/pull/667

**Comment by idsulik** [comment]
Great!

**Comment by jhrotko** [comment]
there are more issues than in #667

**Review by ndeloof — APPROVED** [review]

**Review by jhrotko — APPROVED** [review]

**Pull request merged**
