### PR TITLE
marshal: correctly handle empty shell commands

### PR DESCRIPTION
**Pull request by milas**
It's possible to override an image's entrypoint for service
container's by setting `service.entrypoint`. (Same applies for
image's command.)

In some circumstances, it's desirable to explicitly "clear"
these out from the image. However, currently, if you do specify
`entrypoint: ''` or `entrypoint: []`, when the config is
marshaled, that gets lost because of Go default value handling.

Handling this varies slightly between YAML + JSON:
 * YAML: implement `IsZeroer` interface to specify that only
   `nil` slices should be omittable & `MarshalYAML` to ensure
   that `nil` slices marshal as `null` rather than `[]`
 * JSON: do NOT use `omitempty`, meaning that the result will
   _always_ be present in the marshaled output, unfortunately,
   but it will be correct!

This preserves compatibility and "pretty" serialization for
YAML at the expense of some slightly subtle marshalling
semantics.

### CODE REVIEW

**Comment by milas** [comment]
See docker/compose#9634 for more context/motivation

**Comment by milas** [comment]
Reviewers, for your sanity, view with whitespace changes ignored: https://github.com/compose-spec/compose-go/pull/298/files?diff=split&w=1

(`types.go` has a bunch of fields moving around due to `gofmt` alignment changes which makes it really annoying to read)

**Comment by milas** [comment]
Marked this as ready for review - no changes, but I didn't hear any major concerns out-of-band with this approach 🙃

**Review by glours — APPROVED** [review]
Sounds go to me, just waiting for @ndeloof review to be sure there isn't hidden cases we are missing

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
