### PR TITLE
Cleanup unused types

### LINKED ISSUE #11: remove UnsupportedProperties / DeprecatedProperties / ForbiddenProperties
compose-go do define `types.UnsupportedProperties`, `types.DeprecatedProperties` and `types.ForbiddenProperties` which are actually only used by https://github.com/docker/cli and should not be part of reference library as "supported properties" is implementation specific

### PR DESCRIPTION
**Pull request by bruno-oliveira**
Cleans up unused, deprecated and forbidden properties. Fixes #11

### CODE REVIEW

**Comment by ndeloof** [comment]
Thansk for contributing. Isn't this the same objective as https://github.com/compose-spec/compose-go/pull/28 ?

**Comment by bruno-oliveira** [comment]
Seems like it is, at least partially, but, should it done together? Or is this one a separate issue that addresses only part of the problem in #28? So, if this is done in isolation, can #28 be picked up from there?

**Comment by ndeloof** [comment]
Happy to get your review on #28 then we could merged it

**Comment by bruno-oliveira** [comment]
It looks good to me!

**Comment by bruno-oliveira** [comment]
Since this one requires a single approval maybe it can be merged and then 28?

**Pull request merged**
