### PR TITLE
prefer canonical transform vs DecodeMapStructure

### PR DESCRIPTION
**Pull request by ndeloof**
Avoid use of DecodeMapstructure when we can just make yaml tree canonical

### CODE REVIEW

**Comment by ndeloof** [comment]
I haven't removed DeviceCount#DecodeMapstructure which handle this case

**Comment by glours** [comment]
I just see that, and the `all` is converted to `-1` so it's fine for me 👍

**Review by glours — APPROVED** [review]
LGTM

**Comment by ndeloof** [comment]
to be debated such moby-specific tweaks should live in this repository, or must move to docker specific implementation as docker/compose

**Pull request merged**
