### PR TITLE
Remove only full line comments to avoid variable interpolation on this ones

### PR DESCRIPTION
**Pull request by ulyssessouza**
This is due to the Marshal and Unmarshal methods
also remove double quotes from strings.
This breaks empty strings turning it into `nil` values.

PTAL @lorenrh

Signed-off-by: Ulysses Souza <ulyssessouza@gmail.com>

### CODE REVIEW

**Review by lorenrh — APPROVED** [review]
Thanks!

**Review by StefanScherer — APPROVED** [review]
LGTM

**Review by rumpl — APPROVED** [review]

**Comment by ndeloof** [comment]
LGTM but then we need another way to remove comments :'(

**Comment by ndeloof** [comment]
I guess unmarshall+marshall way to drop comments also caused https://github.com/docker/compose-cli/issues/2036

**Comment by ndeloof** [comment]
I suggest `removeYamlComments` is kept but implementation just drop lines starting by `#`. This won't remove all comments, but at least the most obvious ones where users might have documented usages with some command line examples

**Review by ndeloof — APPROVED** [review]

**Pull request merged**
